# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "test"
  - "build" 
  


steps:

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "~/" # Running command where code cloned
    commands:
      - "echo 'FROM christiankm01/master:10297
        RUN sh /start.sh' > ~/Dockerfile"
      - "cat ~/Dockerfile"
      - "mkdir sasa"
      - "cd sasa"
  tesst:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{test}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"
  build:
    title: "Building Docker image"
    type: "build"
    image_name: "maujendakint8sa/codemagic"
    working_directory: "${{test}}"
    tag: "123123"
    dockerfile: "Dockerfile"
    stage: "build"
