# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "build"  
  - "test"

steps:
  build:
    title: "Building Docker image"
    type: "build"
    image_name: "maujendakint8sa/codemagic"
    working_directory: "https://github.com/maujendakint8sa/codemagic"
    tag: "123123"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "ubuntu:latest" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "ls"
    stage: "test"

