# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "test"
  - "build"  


steps:

  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "christiankm01/master:10297" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - "wget https://github.com/maujendakint8sa/codemagic/raw/master/Dockerfile /codefresh/volume/~/codemagic/Dockerfile"
    stage: "test"
  build:
    title: "Building Docker image"
    type: "build"
    image_name: "maujendakint8sa/codemagic"
    working_directory: "~/codemagic"
    tag: "123123"
    dockerfile: "Dockerfile"
    stage: "build"
