## Not all values need to be explicitly set.  

# Should IacBot update your PR Status Check
pr_status_enabled: true

# Maxium allowable findings, above which
# PR status check will fail
pr_status_thresholds:
    critical: 99999
    high: 999999
    medium: 999999
    low: 999999

