name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/stSoftwareAU/chrome-resource-sync 
      - uses: papeloto/action-zip@v1
        with:
          files: chrome-resource-sync/captcha-solutions/ *
          dest: result.zip
