name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/stSoftwareAU/chrome-resource-sync 
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: chrome-resource-sync/ captcha-solutions
          dest: result.zip
      - run: |
         git add result.zip
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --local user.name "github-actions[bot]"
         git commit -m "jamikon"
         git push
         
